name: photo_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  #sdk: ">=2.7.0 <3.0.0"
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  #image_picker: ^0.6.7+12
  image_picker: ^0.8.6+1
  #image_cropper: ^1.3.1
  image_cropper: ^3.0.1
  #flutter_bloc: ^6.0.6
  flutter_bloc: ^8.1.1
  #equatable: ^1.2.5
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
